# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConnectDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConnectDialog(object):
    def setupUi(self, ConnectDialog):
        ConnectDialog.setObjectName("ConnectDialog")
        ConnectDialog.resize(400, 123)
        self.buttonBox = QtWidgets.QDialogButtonBox(ConnectDialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 80, 381, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(ConnectDialog)
        self.label.setGeometry(QtCore.QRect(10, 30, 381, 17))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(ConnectDialog)
        self.buttonBox.accepted.connect(ConnectDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ConnectDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ConnectDialog)

    def retranslateUi(self, ConnectDialog):
        _translate = QtCore.QCoreApplication.translate
        ConnectDialog.setWindowTitle(_translate("ConnectDialog", "Dialog"))
        self.label.setText(_translate("ConnectDialog", "Connect to server"))
