# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConnectionDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConnectionDialog(object):
    def setupUi(self, ConnectionDialog):
        ConnectionDialog.setObjectName("ConnectionDialog")
        ConnectionDialog.resize(400, 350)
        self.buttonBox = QtWidgets.QDialogButtonBox(ConnectionDialog)
        self.buttonBox.setGeometry(QtCore.QRect(0, 310, 401, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.hostEdit = QtWidgets.QLineEdit(ConnectionDialog)
        self.hostEdit.setGeometry(QtCore.QRect(10, 90, 381, 31))
        self.hostEdit.setObjectName("hostEdit")
        self.label_1 = QtWidgets.QLabel(ConnectionDialog)
        self.label_1.setGeometry(QtCore.QRect(10, 70, 151, 17))
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(ConnectionDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 151, 17))
        self.label_2.setObjectName("label_2")
        self.usernameEdit = QtWidgets.QLineEdit(ConnectionDialog)
        self.usernameEdit.setGeometry(QtCore.QRect(10, 150, 381, 31))
        self.usernameEdit.setObjectName("usernameEdit")
        self.label_3 = QtWidgets.QLabel(ConnectionDialog)
        self.label_3.setGeometry(QtCore.QRect(10, 190, 151, 17))
        self.label_3.setObjectName("label_3")
        self.passwordEdit = QtWidgets.QLineEdit(ConnectionDialog)
        self.passwordEdit.setGeometry(QtCore.QRect(10, 210, 381, 31))
        self.passwordEdit.setObjectName("passwordEdit")
        self.label_4 = QtWidgets.QLabel(ConnectionDialog)
        self.label_4.setGeometry(QtCore.QRect(10, 250, 151, 17))
        self.label_4.setObjectName("label_4")
        self.portEdit = QtWidgets.QLineEdit(ConnectionDialog)
        self.portEdit.setGeometry(QtCore.QRect(10, 270, 381, 31))
        self.portEdit.setObjectName("portEdit")
        self.label_5 = QtWidgets.QLabel(ConnectionDialog)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 151, 17))
        self.label_5.setObjectName("label_5")
        self.connectionNameEdit = QtWidgets.QLineEdit(ConnectionDialog)
        self.connectionNameEdit.setGeometry(QtCore.QRect(10, 30, 381, 31))
        self.connectionNameEdit.setObjectName("connectionNameEdit")

        self.retranslateUi(ConnectionDialog)
        self.buttonBox.accepted.connect(ConnectionDialog.accept)
        self.buttonBox.rejected.connect(ConnectionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ConnectionDialog)

    def retranslateUi(self, ConnectionDialog):
        _translate = QtCore.QCoreApplication.translate
        ConnectionDialog.setWindowTitle(_translate("ConnectionDialog", "Dialog"))
        self.label_1.setText(_translate("ConnectionDialog", "Server"))
        self.label_2.setText(_translate("ConnectionDialog", "Username"))
        self.label_3.setText(_translate("ConnectionDialog", "Password"))
        self.label_4.setText(_translate("ConnectionDialog", "Port"))
        self.label_5.setText(_translate("ConnectionDialog", "Connection name"))
